# -*- coding: utf-8 -*-
"""
Created on 2022-05-23 01:09:51
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class BaseItem(Item):

    def __init__(self, *args, **kwargs):

        self.amount = kwargs.get('amount')             # 成交额
        self.amplitude = kwargs.get('amplitude')       # 振幅
        self.close = kwargs.get('close')               # 收盘价
        self.code = kwargs.get('code')                 # 股拍哦代码
        self.datetime = kwargs.get('datetime')         # 日期
        self.high = kwargs.get('high')                 # 最高价
        self.low = kwargs.get('low')                   # 最低价
        self.market = kwargs.get('market')             # 市场
        self.name = kwargs.get('name')                 # 股票名称
        self.open = kwargs.get('open')                 # 开盘价
        self.pre_close = kwargs.get('pre_close')       # 昨收价
        self.range = kwargs.get('range')               # 涨跌幅
        self.range_money = kwargs.get('range_money')   # 涨跌额
        self.tornover = kwargs.get('tornover')         # 换手率
        self.volume = kwargs.get('volume')             # 成交量
        self.period = kwargs.get('period')             # 成交量
        self.type = kwargs.get('type')                 # 成交量

    def pre_to_db(self):
        """
        入库前的处理
        """

        self.market = '中国A股'
        self.open = eval(self.open) if self.open else 0.0
        self.close = eval(self.close) if self.close else 0.0
        self.high = eval(self.high) if self.high else 0.0
        self.low = eval(self.low) if self.low else 0.0
        self.volume = eval(self.volume) if self.volume else 0.0
        self.amount = eval(self.amount) if self.amount else 0.0
        self.amplitude = eval(self.amplitude) if self.amplitude else 0.0
        self.range = eval(self.range) if self.range else 0.0
        self.range_money = eval(self.range_money) if self.range_money else 0.0
        self.tornover = eval(self.tornover) if self.tornover else 0.0


class Block1DItem(BaseItem):
    """
    This class was generated by feapder
    command: feapder create -i block_1d 1
    """

    __table_name__ = "block_1d"


class Block1MItem(BaseItem):
    """
    This class was generated by feapder
    command: feapder create -i block_1m 1
    """

    __table_name__ = "block_1m"


class Block5MItem(BaseItem):
    """
    This class was generated by feapder
    command: feapder create -i block_5m 1
    """

    __table_name__ = "block_5m"


class Block15MItem(BaseItem):
    """
    This class was generated by feapder
    command: feapder create -i block_15m 1
    """

    __table_name__ = "block_15m"


class Block30MItem(BaseItem):
    """
    This class was generated by feapder
    command: feapder create -i block_30m 1
    """

    __table_name__ = "block_30m"


class Block60MItem(BaseItem):
    """
    This class was generated by feapder
    command: feapder create -i block_60m 1
    """

    __table_name__ = "block_60m"


class Block120MItem(BaseItem):
    """
    This class was generated by feapder
    command: feapder create -i block_120m 1
    """

    __table_name__ = "block_120m"
