# -*- coding: utf-8 -*-
"""
Created on 2022-05-22 01:00:02
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class FundListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i fund_list 1
    """

    __table_name__ = "fund_list"

    def __init__(self, *args, **kwargs):
        self.code = kwargs.get('code')
        self.establish_date = kwargs.get('establish_date')
        # self.id = kwargs.get('id')
        self.name = kwargs.get('name')
        self.service_charge = kwargs.get('service_charge')
        self.type = kwargs.get('type')
