# -*- coding: utf-8 -*-
"""
Created on 2022-05-22 22:06:10
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class FundScaleItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i fund_scale 1
    """

    __table_name__ = "fund_scale"

    def __init__(self, *args, **kwargs):

        self.apply = kwargs.get('apply')               # 期间申购（份）
        self.change_rate = kwargs.get('change_rate')   # 规模变化率
        self.code = kwargs.get('code')
        self.date = kwargs.get('date')
        self.redeam = kwargs.get('redeam')             # 期间赎回（份）
        self.scale = kwargs.get('scale')               # 期间规模（元）
        self.total = kwargs.get('total')               # 期间总份额（份）

    def pre_to_db(self):
        """
        入库前的处理
        """

        # 如果有控格，则去除空格
        self.apply = self.apply.strip() if self.apply else self.apply
        self.change_rate = self.change_rate.strip() if self.change_rate else self.change_rate
        self.redeam = self.redeam.strip() if self.redeam else self.redeam
        self.scale = self.scale.strip() if self.scale else self.scale
        self.total = self.total.strip() if self.total else self.total
        # 转化成float，换算单位
        self.apply = float(self.apply) * pow(10, 9) if self.apply and '-' not in self.apply else 0.0
        self.redeam = float(self.redeam) * pow(10, 9) if self.redeam and '-' not in self.redeam else 0.0
        self.scale = float(self.scale) * pow(10, 9) if self.scale and '-' not in self.scale else 0.0
        self.total = float(self.total) * pow(10, 9) if self.total and '-' not in self.total else 0.0
