# -*- coding: utf-8 -*-
"""
Created on 2022-05-22 01:00:02
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class FundListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i fund_list 1
    """

    __table_name__ = "fund_list"

    def __init__(self, *args, **kwargs):

        self.code = kwargs.get('code')
        self.establish_date = kwargs.get('establish_date')
        self.name = kwargs.get('name')
        self.service_charge = kwargs.get('service_charge')
        self.type = kwargs.get('type')

    def pre_to_db(self):
        """
        入库前的处理
        """

        self.code = self.code.strip() if self.code else self.code
        self.name = self.name.strip() if self.name else self.name
        self.service_charge = self.service_charge.strip() if self.service_charge else self.service_charge
        self.type = self.type.strip() if self.type else self.type
